bias: 0.0
case: local
colors:
- - tab:blue
  - lightblue
- - tab:orange
  - lightorange
- - tab:red
  - red
- - tab:green
  - lightgreen
corrlength: 2
figformat: pdf
livetime: 2.154434690031884
livetimes:
- 0.01
- 0.021544346900318832
- 0.046415888336127774
- 0.1
- 0.21544346900318834
- 0.46415888336127775
- 1.0
- 2.154434690031884
- 4.641588833612778
- 10.0
- 21.544346900318832
- 46.41588833612777
- 100.0
local:
  path: /home/katrin/Documents
  path_pksflare: /home/katrin/Documents/nuisance_summary/PKS_flare
magnitude: 10
model: crab_cutoff
norm: 0.0
parameter_names:
- - amplitude
  - index
- - amplitude
  - lambda_
- - lambda_
  - index
resolution: 0
source: PKSflare
sys: Bkgext
tilt: 0.0
wecap:
  path: /home/vault/caph/mppi062h/repositories/HESS_3Dbkg_syserror/2-error_in_dataset
  path_pksflare: /home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare
woody:
  path: /home/vault/caph/mppi062h/repositories/HESS_3Dbkg_syserror/2-error_in_dataset
  path_pksflare: /home/hpc/caph/mppi045h/3D_analysis/N_parameters_in_L/nuisance_summary/Crab
zero: 1.0e-12
